---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.19.36

platforms:
  - name: ubuntu-16.04

suites:
  - name: wurm
    driver:
      vm_hostname: 'wurm.local'
      network:
        - ["private_network", {ip: "192.168.224.101"}]
      customize:
        memory: 1024
        cpus: 2
        cpuexecutioncap: 80
    run_list:
      - recipe[chef-solo::default]
    attributes:
